import { EventRecord, ProductRecord } from "./types";

export const events: EventRecord[] = [
  {
    id: "evt_1001",
    slug: "aria-night-live-nyc",
    title: "Aria Night Live",
    city: "New York",
    celebrity: "Aria Vel",
    startAt: "2026-06-07T20:00:00-04:00",
    venueName: "Grand Orbit Arena",
    eventType: "reserved_seating",
    status: "published",
    refundPolicy: "Refunds available up to 7 days before showtime. Non-refundable after that period.",
    resalePolicy: "Resale allowed only through authorized marketplace with capped markup.",
    imageAlt: "Aria Vel headlining New York",
    ticketTiers: [
      { id: "tier_aria_vip", name: "VIP", priceMinor: 19900, feeMinor: 1600, vatMinor: 1800, quantityAvailable: 28 },
      { id: "tier_aria_floor", name: "Floor", priceMinor: 12900, feeMinor: 1200, vatMinor: 1170, quantityAvailable: 86 },
      { id: "tier_aria_std", name: "Standard", priceMinor: 7900, feeMinor: 900, vatMinor: 710, quantityAvailable: 154 },
    ],
  },
  {
    id: "evt_1002",
    slug: "zayn-vibe-sessions-miami",
    title: "Vibe Sessions",
    city: "Miami",
    celebrity: "Zayn Koro",
    startAt: "2026-06-11T19:30:00-04:00",
    venueName: "South Bay Dome",
    eventType: "general_admission",
    status: "published",
    refundPolicy: "Full refund for venue cancellation or date changes.",
    resalePolicy: "Transfers allowed until 24 hours before event start.",
    imageAlt: "Zayn Koro live in Miami",
    ticketTiers: [
      { id: "tier_zayn_ga", name: "General Admission", priceMinor: 6900, feeMinor: 800, vatMinor: 620, quantityAvailable: 250 },
      { id: "tier_zayn_plus", name: "GA Plus", priceMinor: 9900, feeMinor: 1000, vatMinor: 890, quantityAvailable: 120 },
    ],
  },
  {
    id: "evt_1003",
    slug: "nova-skyline-tour-la",
    title: "Skyline Tour",
    city: "Los Angeles",
    celebrity: "Nova Rae",
    startAt: "2026-06-18T21:00:00-07:00",
    venueName: "Moonlight Pavilion",
    eventType: "reserved_seating",
    status: "published",
    refundPolicy: "Refunds accepted within 48 hours of purchase if event date is over 14 days away.",
    resalePolicy: "One transfer per ticket, identity checks may apply.",
    imageAlt: "Nova Rae skyline tour poster",
    ticketTiers: [
      { id: "tier_nova_pit", name: "Pit", priceMinor: 15900, feeMinor: 1400, vatMinor: 1430, quantityAvailable: 42 },
      { id: "tier_nova_bal", name: "Balcony", priceMinor: 9200, feeMinor: 1000, vatMinor: 830, quantityAvailable: 96 },
    ],
  },
  {
    id: "evt_1004",
    slug: "echo-beats-dallas",
    title: "Echo Beats",
    city: "Dallas",
    celebrity: "Echo Rune",
    startAt: "2026-06-23T20:30:00-05:00",
    venueName: "Pulse Hall",
    eventType: "general_admission",
    status: "published",
    refundPolicy: "No refunds except in case of cancellation.",
    resalePolicy: "No resale, transfers disabled for this event.",
    imageAlt: "Echo Rune beats tour in Dallas",
    ticketTiers: [{ id: "tier_echo_ga", name: "General Admission", priceMinor: 5400, feeMinor: 650, vatMinor: 490, quantityAvailable: 310 }],
  },
];

export const products: ProductRecord[] = [
  {
    id: "fc-101",
    slug: "aria-prism-card",
    name: "Aria Prism Card",
    rarity: "Limited Edition",
    tag: "Drop",
    priceMinor: 3900,
    currency: "USD",
    description: "A holo-foil collectors card featuring an exclusive backstage portrait and signed authenticity seal.",
    edition: "Edition 07/100",
    authenticityCode: "APC-48291",
    delivery: "Instant digital preview plus physical packaging within 3-5 business days.",
    stockLabel: "Only 12 left",
  },
  {
    id: "fc-102",
    slug: "nova-gold-foil",
    name: "Nova Gold Foil",
    rarity: "Exclusive",
    tag: "Top Pick",
    priceMinor: 4900,
    currency: "USD",
    description: "Premium gold-foil card with alternate artwork and a numbered collector certificate.",
    edition: "Edition 21/75",
    authenticityCode: "NGF-77812",
    delivery: "Digital vault access now, physical card ships next week.",
    stockLabel: "Limited release",
  },
  {
    id: "fc-103",
    slug: "zayn-legacy-print",
    name: "Zayn Legacy Print",
    rarity: "Rare",
    priceMinor: 3200,
    currency: "USD",
    description: "A cinematic print inspired by the Legacy Sessions tour and available in a numbered run.",
    edition: "Edition 44/150",
    authenticityCode: "ZLP-11043",
    delivery: "Print delivered digitally today, with framed shipping available.",
    stockLabel: "Ready to ship",
  },
  {
    id: "fc-104",
    slug: "echo-neon-set",
    name: "Echo Neon Set",
    rarity: "Limited Edition",
    tag: "Low Stock",
    priceMinor: 4400,
    currency: "USD",
    description: "A bundled collector set with two neon-themed cards and a VIP hologram sticker.",
    edition: "Edition 03/60",
    authenticityCode: "ENS-29011",
    delivery: "Physical delivery in 2-3 days plus digitalunboxing content.",
    stockLabel: "Low stock",
  },
];

export function getLowestEventPrice(event: EventRecord): number {
  return Math.min(...event.ticketTiers.map((tier) => tier.priceMinor));
}